const products = [
  {
    _id: "1",
    name: "Macbook Pro",
    image: "/images/macbook.jpeg",
    description:
      "The new MacBook Pro delivers game-changing performance for pros. With the powerful M1 Pro chip to power through your work while enjoying incredible",
    brand: "Apple",
    category: "Electronics",
    price: 1299,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "1",
    name: "Macbook Pro",
    image: "/images/macbook.jpeg",
    description:
      "The new MacBook Pro delivers game-changing performance for pros. With the powerful M1 Pro chip to power through your work while enjoying incredible",
    brand: "Apple",
    category: "Electronics",
    price: 1299,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "1",
    name: "Macbook Pro",
    image: "/images/macbook.jpeg",
    description:
      "The new MacBook Pro delivers game-changing performance for pros. With the powerful M1 Pro chip to power through your work while enjoying incredible",
    brand: "Apple",
    category: "Electronics",
    price: 1299,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "1",
    name: "Macbook Pro",
    image: "/images/macbook.jpeg",
    description:
      "The new MacBook Pro delivers game-changing performance for pros. With the powerful M1 Pro chip to power through your work while enjoying incredible",
    brand: "Apple",
    category: "Electronics",
    price: 1299,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "1",
    name: "Macbook Pro",
    image: "/images/macbook.jpeg",
    description:
      "The new MacBook Pro delivers game-changing performance for pros. With the powerful M1 Pro chip to power through your work while enjoying incredible",
    brand: "Apple",
    category: "Electronics",
    price: 1299,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "1",
    name: "Macbook Pro",
    image: "/images/macbook.jpeg",
    description:
      "The new MacBook Pro delivers game-changing performance for pros. With the powerful M1 Pro chip to power through your work while enjoying incredible",
    brand: "Apple",
    category: "Electronics",
    price: 1299,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "1",
    name: "Macbook Pro",
    image: "/images/macbook.jpeg",
    description:
      "The new MacBook Pro delivers game-changing performance for pros. With the powerful M1 Pro chip to power through your work while enjoying incredible",
    brand: "Apple",
    category: "Electronics",
    price: 1299,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "1",
    name: "Macbook Pro",
    image: "/images/macbook.jpeg",
    description:
      "The new MacBook Pro delivers game-changing performance for pros. With the powerful M1 Pro chip to power through your work while enjoying incredible",
    brand: "Apple",
    category: "Electronics",
    price: 1299,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "1",
    name: "Macbook Pro",
    image: "/images/macbook.jpeg",
    description:
      "The new MacBook Pro delivers game-changing performance for pros. With the powerful M1 Pro chip to power through your work while enjoying incredible",
    brand: "Apple",
    category: "Electronics",
    price: 1299,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
];

export default products;
